"use client"
import { HelpCircle } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Separator } from "@/components/ui/separator"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"

interface DocumentEditorProps {
  activeSection: string
  onSectionChange: (section: string) => void
}

export function DocumentEditor({ activeSection, onSectionChange }: DocumentEditorProps) {
  return (
    <div className="flex flex-col h-full overflow-hidden">
      <div className="border-b p-2">
        <Tabs value={activeSection} onValueChange={onSectionChange}>
          <TabsList className="w-full">
            {sections.map((section) => (
              <TabsTrigger key={section.id} value={section.id} className="flex-1">
                <div className="flex items-center gap-1">
                  <span>{section.label}</span>
                  {section.status === "complete" && <div className="w-2 h-2 rounded-full bg-green-500" />}
                  {section.status === "in-progress" && <div className="w-2 h-2 rounded-full bg-blue-500" />}
                  {section.status === "needs-attention" && <div className="w-2 h-2 rounded-full bg-amber-500" />}
                </div>
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </div>

      <div className="border-b p-2 bg-white">
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm">
            Bold
          </Button>
          <Button variant="outline" size="sm">
            Italic
          </Button>
          <Button variant="outline" size="sm">
            Underline
          </Button>
          <Separator orientation="vertical" className="h-8" />
          <Button variant="outline" size="sm">
            Bullet List
          </Button>
          <Button variant="outline" size="sm">
            Numbered List
          </Button>
          <Separator orientation="vertical" className="h-8" />
          <Button variant="outline" size="sm">
            Heading
          </Button>
          <Button variant="outline" size="sm">
            Paragraph
          </Button>
        </div>
      </div>

      <div className="flex-1 overflow-auto p-6">
        {sections.map((section) => (
          <TabsContent key={section.id} value={section.id} className="mt-0 h-full">
            <div className="space-y-6">
              <h2 className="text-2xl font-bold">{section.title}</h2>

              {section.content.map((paragraph, index) => (
                <div key={index} className="relative group">
                  <p
                    className={`text-sm leading-relaxed ${paragraph.type === "ai" ? "bg-blue-50 border-l-2 border-blue-500 pl-3 py-2 rounded-sm" : ""}`}
                  >
                    {paragraph.text}
                  </p>

                  <div className="absolute right-0 top-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Button variant="ghost" size="icon" className="h-6 w-6">
                            <HelpCircle className="h-4 w-4" />
                          </Button>
                        </TooltipTrigger>
                        <TooltipContent side="left">
                          <p className="text-xs max-w-xs">
                            {paragraph.type === "ai"
                              ? "This content was generated by AI based on your company data and SEC requirements."
                              : "This content was manually edited."}
                          </p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  </div>
                </div>
              ))}
            </div>
          </TabsContent>
        ))}
      </div>
    </div>
  )
}

const sections = [
  {
    id: "item1",
    label: "Item 1",
    title: "Item 1: Business",
    status: "complete",
    content: [
      {
        type: "manual",
        text: 'Acme Corporation (the "Company," "we," "us," or "our") is a leading provider of innovative technology solutions for businesses worldwide. Founded in 1985, we design, develop, and deliver cloud-based software applications that help organizations streamline operations, enhance productivity, and drive growth.',
      },
      {
        type: "ai",
        text: "Our principal executive offices are located at 123 Tech Boulevard, San Francisco, California 94105. Our telephone number is (555) 123-4567, and our website address is www.acmecorp.com. Information contained on our website is not incorporated by reference into this Annual Report on Form 10-K.",
      },
      {
        type: "manual",
        text: "We operate in three reportable segments: Enterprise Solutions, Small Business Services, and Consumer Applications. Our Enterprise Solutions segment provides comprehensive software platforms for large organizations with complex needs. Our Small Business Services segment offers streamlined versions of our core technologies tailored to the needs of growing businesses. Our Consumer Applications segment develops user-friendly applications for individual users.",
      },
      {
        type: "ai",
        text: "For the fiscal year ended December 31, 2023, we generated $1.2 billion in revenue, representing a 15% increase compared to the prior fiscal year. Enterprise Solutions accounted for 65% of our revenue, Small Business Services accounted for 25%, and Consumer Applications accounted for the remaining 10%.",
      },
    ],
  },
  {
    id: "item1a",
    label: "Item 1A",
    title: "Item 1A: Risk Factors",
    status: "in-progress",
    content: [
      {
        type: "ai",
        text: "Investing in our securities involves a high degree of risk. You should carefully consider the risks and uncertainties described below, together with all of the other information in this Annual Report on Form 10-K, including our consolidated financial statements and related notes, before making a decision to invest in our securities. The risks and uncertainties described below may not be the only ones we face. If any of the risks actually occur, our business, financial condition, operating results, and prospects could be materially and adversely affected. In that event, the market price of our common stock could decline, and you could lose part or all of your investment.",
      },
      {
        type: "ai",
        text: "Risks Related to Our Business and Industry\n\nIf we are unable to compete effectively, our business, financial condition, and results of operations could be adversely affected. The markets for our products and services are highly competitive, and we expect competition to increase in the future. We face competition from both established and emerging companies that offer similar products and services. Many of our competitors have longer operating histories, greater name recognition, larger customer bases, and significantly greater financial, technical, marketing, and other resources than we do.",
      },
    ],
  },
  {
    id: "item7",
    label: "Item 7",
    title: "Item 7: Management's Discussion and Analysis",
    status: "needs-attention",
    content: [
      {
        type: "manual",
        text: "The following discussion and analysis of our financial condition and results of operations should be read in conjunction with our consolidated financial statements and related notes included elsewhere in this Annual Report on Form 10-K. This discussion contains forward-looking statements that involve risks and uncertainties. Our actual results could differ materially from those discussed below.",
      },
      {
        type: "ai",
        text: "Overview\n\nWe are a leading provider of innovative technology solutions for businesses worldwide. Our revenue is primarily derived from subscription fees for our cloud-based software applications, professional services related to implementation and training, and support services. For the fiscal year ended December 31, 2023, we generated $1.2 billion in revenue, representing a 15% increase compared to the prior fiscal year.",
      },
    ],
  },
  {
    id: "item8",
    label: "Item 8",
    title: "Item 8: Financial Statements",
    status: "not-started",
    content: [
      {
        type: "manual",
        text: "This section will contain the audited financial statements and supplementary data.",
      },
    ],
  },
]
